include:
  - remote: https://raw.githubusercontent.com/ika-rwth-aachen/docker-ros/refs/heads/deprecate-ros1/.gitlab-ci/docker-ros.yml

variables:
  BASE_IMAGE: rwthika/ros2:jazzy
  RMW_IMPLEMENTATION: rmw_zenoh_cpp
  DOCKER_ROS_GIT_REF: deprecate-ros1
  TARGET: dev,run
  PLATFORM: arm64,amd64
  COMMAND: ros2 launch simple_planner simple_planner.launch.py