/**:
  ros__parameters:

    #### general parameters
    trajectory_frame_id: base_link  # Frame ID of output trajectory
    fixed_over_time_frame_id: map   # Frame ID of frame that is fixed over time for finding temporal transforms
    frequency: 10.0
    route_timeout: 1.0              # time after which a received route is considered invalid (s) (use -1 for no timeout)

    #### trajectory generation parameters
    trajectory_horizon: 6.0         # covered time horizon of the published trajectory (s)
    n_states: 61                    # number of states in published trajectory
    internal_route_update: False    # true: the route is received once and then updated locally in this node (cutting off the traveled route, etc.); false: the route is received cyclically (it is updated externally).
    interpolation_type: 1           # 0: linear, 1: cubic spline
    v_ref: 3.0                      # reference velocity (m/s)
    a_max_decel: -0.5               # maximum deceleration for braking at stop lines or end of route (m/s^2)

    #### traffic light parameters
    consider_traffic_lights: True   # true: planner will consider traffic lights; false: planner will ignore traffic lights
    offset_to_stop_line: 0.0        # additional distance to stop in front of a stop line (m) (default: 0.0 -> stops with front of vehicle at stop line)