/**:
  ros__parameters:

    #### general parameters
    trajectory_frame_id: base_link  # Frame ID of output trajectory
    fixed_over_time_frame_id: map   # Frame ID of frame that is fixed over time for finding temporal transforms
    frequency: 10.0
    
    #### trajectory generation parameters
    static_route: True              # true: incoming route/path is static; false: incoming route/path is dynamic
    trajectory_horizon: 6.0         # planning horizon (s)
    n_states: 61                    # number of states in trajectory
    v_ref: 3.0                      # reference velocity (m/s)

    a_max_decel: -0.5               # maximum deceleration for braking at stop lines or end of route (m/s^2)

    #### traffic light parameters
    consider_traffic_lights: False  # true: planner will consider traffic lights; false: planner will ignore traffic lights
    offset_to_stop_line: 0.0        # additional distance to stop in front of a stop line (m) (default: 0.0 -> stops with front of vehicle at stop line)

    use_sim_time: True


    # ros2 launch simple_planner simple_planner.launch.py ego_data_topic:=/carla_its_adapter/ego_data route_topic:=/route_planning/route trajectory_topic:=/planning/reference_trajectory