/**:
  ros__parameters:
    frequency: 100.0 # Hz
    p_longitudinal: 1.0
    i_longitudinal: 0.015
    d_longitudinal: 1.0
    p_lateral: 0.9
    i_lateral: 0.005
    d_lateral: 1.0
    lookahead_time_pid: 2.0 # s
    use_sim_time: True