openadservice:
  name: simple-planner
  image: ghcr.io/openads-project/simple_planner:v1.3.0
  env:
    # --- name ------
    NAMESPACE: /
    NAME: simple_planner
    # --- inputs ----
    EGO_DATA_TOPIC: ~/ego_data
    OBJECT_LIST_TOPIC: ~/object_list
    ROUTE_TOPIC: ~/route
    GRID_MAP_TOPIC: ~/grid_map
    # --- outputs ---
    TRAJECTORY_TOPIC: ~/trajectory
    OBJECT_INTERACTION_MARKERS_TOPIC: ~/viz/object_interaction_markers
    # --- other -----
    LEFT_TURN_INDICATOR_SERVICE: ~/enable_left_turn_indicator
    RIGHT_TURN_INDICATOR_SERVICE: ~/enable_right_turn_indicator
    HAZARD_LIGHTS_SERVICE: ~/enable_hazard_lights
    LOG_LEVEL: info
    USE_SIM_TIME: false
    PARAMS: /docker-ros/ws/install/simple_planner/share/simple_planner/config/params.yml
    TRACE: false
  args:
  - /bin/bash
  - -ic
  - |
    ros2 launch simple_planner simple_planner.launch.py \
      namespace:=${NAMESPACE} \
      name:=${NAME} \
      log_level:=${LOG_LEVEL} \
      use_sim_time:=${USE_SIM_TIME} \
      params:=${PARAMS} \
      trace:=${TRACE} \
      ego_data_topic:=${EGO_DATA_TOPIC} \
      object_list_topic:=${OBJECT_LIST_TOPIC} \
      route_topic:=${ROUTE_TOPIC} \
      grid_map_topic:=${GRID_MAP_TOPIC} \
      trajectory_topic:=${TRAJECTORY_TOPIC} \
      object_interaction_markers_topic:=${OBJECT_INTERACTION_MARKERS_TOPIC} \
      left_turn_indicator_service:=${LEFT_TURN_INDICATOR_SERVICE} \
      right_turn_indicator_service:=${RIGHT_TURN_INDICATOR_SERVICE} \
      hazard_lights_service:=${HAZARD_LIGHTS_SERVICE}
  rosParamFileMountPath: /docker-ros/ws/install/simple_planner/share/simple_planner/config/params.yml
  rosParamFileData: null
